// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQBQSxGjr8bZZHsRZAsvYDRVLQH_r7vt0',
    appId: '1:483858559173:android:76d9ac376d449ace9f80ac',
    messagingSenderId: '483858559173',
    projectId: 'tree-platform-7ae17',
    storageBucket: 'tree-platform-7ae17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpwYUHpbfbrGniu7Stvad385S_FDmZkLQ',
    appId: '1:483858559173:ios:96740dd6e718f95c9f80ac',
    messagingSenderId: '483858559173',
    projectId: 'tree-platform-7ae17',
    storageBucket: 'tree-platform-7ae17.firebasestorage.app',
    androidClientId: '483858559173-59bl5h8qreb39ll4ekvf7nu5eoecjv49.apps.googleusercontent.com',
    iosClientId: '483858559173-7ofkchqlcip69mpe59boilgdg22opab6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tressleApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpwYUHpbfbrGniu7Stvad385S_FDmZkLQ',
    appId: '1:483858559173:ios:96740dd6e718f95c9f80ac',
    messagingSenderId: '483858559173',
    projectId: 'tree-platform-7ae17',
    storageBucket: 'tree-platform-7ae17.firebasestorage.app',
    androidClientId: '483858559173-59bl5h8qreb39ll4ekvf7nu5eoecjv49.apps.googleusercontent.com',
    iosClientId: '483858559173-7ofkchqlcip69mpe59boilgdg22opab6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tressleApp1',
  );
}
